const {testAbs} = require('./tests/abs.js');
const {testAdd} = require('./tests/add.js');
const {testCeil} = require('./tests/ceil.js');
const {testDivide} = require('./tests/divide.js');
const {testFloor} = require('./tests/floor.js');
const {testGcd} = require('./tests/gcd.js');
const {testIsPrime} = require('./tests/isPrime.js');
const {testLCM} = require('./tests/lcm.js');
const {testMax} = require('./tests/max.js');
const {testMean} = require('./tests/mean.js');
const {testMedian} = require('./tests/median.js');
const {testMinFunction} = require('./tests/min.js');
const {testMode} = require('./tests/mode.js');
const {testMultiply} = require('./tests/multiply.js');
const {testPowerFunction} = require('./tests/power.js');
const {testRound} = require('./tests/round.js');
const {testSquare} = require('./tests/square.js');
const {testSquareRoot} = require('./tests/squareRoot.js');
const {testSubtract} = require('./tests/subtract.js');
const {testTrunc} = require('./tests/trunc.js');

testAbs();
testAdd();
testCeil();
testDivide();
testFloor();
testGcd();
testIsPrime();
testLCM();
testMax();
testMean();
testMedian();
testMinFunction();
testMode();
testMultiply();
testPowerFunction();
testRound();
testSquare();
testSquareRoot();
testSubtract();
testTrunc();